import { test, expect } from '@playwright/test';
const person = { id: 'owner', full_name: 'Alex Chen' };
const room = { id: 'g1', course: 'Calculus', date: '2026-10-20', start_time: '09:00', end_time: '12:00', location: 'Library', notes: 'Practice together', status: 'open', max_members: 5, member_count: 1, members: [person], created_by: person };
test('room filters, join failure and retry, roster and desktop layout', async ({ page }, info) => {
  await page.route('**/login', route => route.fulfill({ json: { status: 'success', user_id: 'viewer', user: { id: 'viewer' } } }));
  await page.route('**/users/viewer', route => route.fulfill({ json: { status: 'failed', reason: 'No profile' } }));
  await page.goto('/#login');
  await page.getByLabel('Student ID', { exact: true }).fill('demo');
  await page.getByLabel('Password', { exact: true }).fill('password123');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page).toHaveURL(/#home$/);
  await page.getByRole('link', { name: /Find a study room/ }).click();
  await page.route('**/study-groups?*', route => {
    const query = Object.fromEntries(new URL(route.request().url()).searchParams);
    expect(query).toEqual({ course: 'Calculus', major: 'Computer Science', date: '2026-10-20', start_time: '09:00', end_time: '12:00', location: 'Library', viewer_id: 'viewer' });
    return route.fulfill({ json: { status: 'success', groups: [room] } });
  });
  await page.getByLabel('Course', { exact: true }).fill('Calc');
  await page.getByRole('option', { name: 'Calculus', exact: true }).click();
  await page.getByLabel('Major', { exact: true }).selectOption('Computer Science');
  await page.getByLabel('Date', { exact: true }).fill('2026-10-20');
  await page.getByLabel('Start time').fill('09:00');
  await page.getByRole('button', { name: 'Find rooms', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Enter both times');
  await page.getByLabel('End time').fill('12:00');
  await page.getByLabel('Location', { exact: true }).fill('Library');
  await page.getByRole('button', { name: 'Find rooms', exact: true }).click();
  await expect(page.getByText('4 seats available')).toBeVisible();
  await page.locator('.group-card summary').click();
  await expect(page.getByText('Alex Chen · Host')).toBeVisible();
  let attempts = 0;
  await page.route('**/study-groups/g1/request', route => {
    expect(route.request().postDataJSON()).toEqual({ from_user_id: 'viewer' });
    return route.fulfill({ json: ++attempts === 1 ? { status: 'failed', reason: 'Try again later' } : { status: 'success', request_id: 'req1' } });
  });
  await page.getByRole('button', { name: 'Request to join' }).click();
  await expect(page.getByRole('alert')).toHaveText('Try again later');
  await page.getByRole('button', { name: 'Request to join' }).click();
  await expect(page.getByRole('button', { name: 'Request sent' })).toBeDisabled();
  await expect(page.getByText('1 / 5 members')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: info.outputPath('rooms.png'), fullPage: true });
});
test('create editable capacity, refresh full state and cancel own room', async ({ page }) => {
  await page.route('**/login', route => route.fulfill({ json: { status: 'success', user_id: 'owner', user: { id: 'owner' } } }));
  await page.route('**/users/owner', route => route.fulfill({ json: { status: 'failed' } }));
  await page.goto('/#login');
  await page.getByLabel('Student ID', { exact: true }).fill('demo');
  await page.getByLabel('Password', { exact: true }).fill('password123');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page).toHaveURL(/#home$/);
  await page.getByRole('link', { name: /Find a study room/ }).click();
  await page.getByRole('button', { name: 'Create a room' }).click();
  await page.route('**/study-groups', route => {
    expect(route.request().postDataJSON()).toEqual({ user_id: 'owner', course: 'Calculus', date: '2026-10-20', start_time: '09:00', end_time: '12:00', location: 'Library', notes: '', max_members: 5 });
    return route.fulfill({ json: { status: 'success', group_id: 'g1', group: room } });
  });
  await page.getByLabel('Course', { exact: true }).fill('Calc');
  await page.getByRole('option', { name: 'Calculus', exact: true }).click();
  await page.getByLabel('Maximum members').fill('5');
  await page.getByLabel('Date', { exact: true }).fill('2026-10-20');
  await page.getByLabel('Start time').fill('09:00');
  await page.getByLabel('End time').fill('12:00');
  await page.getByLabel('Location', { exact: true }).fill('Library');
  await page.getByRole('button', { name: 'Publish room' }).click();
  await expect(page.getByRole('status')).toContainText('Study room created');
  await page.route('**/study-groups/g1', route => route.fulfill({ json: { status: 'success', group: { ...room, status: 'full', member_count: 5 } } }));
  await page.getByRole('button', { name: 'Refresh room' }).click();
  await expect(page.getByText('Room full', { exact: true })).toBeVisible();
  await page.route('**/study-groups/g1?user_id=owner', route => { expect(route.request().method()).toBe('DELETE'); return route.fulfill({ json: { status: 'success' } }); });
  page.on('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Cancel room' }).click();
  await expect(page.getByText('Room cancelled', { exact: true })).toBeVisible();
});
test('empty and offline states do not show fictional rooms', async ({ page }) => {
  await page.goto('/#study-groups');
  await page.getByLabel('Course', { exact: true }).fill('Calc');
  await page.getByRole('option', { name: 'Calculus', exact: true }).click();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await expect(page.getByLabel('Course', { exact: true })).toHaveValue('');
  await page.route('**/study-groups?*', route => route.abort());
  await page.getByRole('button', { name: 'Find rooms', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Could not reach');
  await page.route('**/study-groups?*', route => route.fulfill({ json: { status: 'success', groups: [] } }));
  await page.getByRole('button', { name: 'Find rooms', exact: true }).click();
  await expect(page.getByText('No rooms found yet.')).toBeVisible();
  await page.getByRole('button', { name: 'Create a room' }).click();
  await expect(page.getByRole('link', { name: 'Log in', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Publish room' })).toHaveCount(0);
});
